on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'mybranch1'
    paths:
      src/**.py
      
jobs:
  greet:
    runs-on: [ubuntu-latest]
    steps:
      - name: say hi
        run: |
          ls -l
          echo "Hello World2"
          pwd
          ls -l ..
          python ../src/hello.py
   
