on:
  workflow_dispatch:
  push:
    branches:
      - 'main/**'
      - 'feature/**'
      
jobs:
  greet:
    runs-on: [atc-ubuntu-latest]
    steps:
      - name: say hi
        run: |
          echo "Hello World"
   
