on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'mybranch1'
      
jobs:
  greet:
    runs-on: [ubuntu-latest]
    steps:
      - name: say hi
        run: |
          echo "Hello World2"
   
