on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'mybranch1'
      
jobs:
  greet:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: say hi
        run: |
          ls -l
          echo "Hello World2"
          pwd
          ls -l ..
          python src/hello.py
   
